export const MOVIES_LIST_REQUEST = "MOVIES_LIST_REQUEST";
export const MOVIES_LIST_SUCCESS = "MOVIES_LIST_SUCCESS";
export const MOVIES_LIST_FAIL = "MOVIES_LIST_FAIL";

export const MOVIES_LIKE_REQUEST = "MOVIES_LIKE_REQUEST";
export const MOVIES_LIKE_SUCCESS = "MOVIES_LIKE_SUCCESS";
export const MOVIES_LIKE_FAIL = "MOVIES_LIKE_FAIL";





